repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: ^po/POTFILES.in
    -   id: forbid-new-submodules
    -   id: trailing-whitespace

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: ["--skip", "*.po,tests/data/*.json"]

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/doc8
    rev: v1.0.0
    hooks:
    -   id: doc8

-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: poetry run coverage run -m unittest discover tests/
        language: python
        types: [python]
        pass_filenames: false
