#!/bin/bash

VERSION=$(poetry version --short)
BUILDDIR=builddir

[ -d ${BUILDDIR} ] && {
    echo "Removing existing build directory…"
    rm -rf ${BUILDDIR}
}

mkdir ${BUILDDIR}

git archive --prefix=${BUILDDIR}/argos-${VERSION}/ --format=tar.gz HEAD | tar xzf -
pushd ${BUILDDIR}/argos-${VERSION} && debuild -b -tc -us -uc && popd
