#!/bin/bash

VERSION=$(poetry version | cut -d' ' -f 2)

[ -f builddir ] && {
    echo "Removing existing builddir…"
    rm -rf builddir
}

mkdir builddir

git archive --prefix=builddir/argos-${VERSION}/ --format=tar.gz HEAD | tar xzf -
pushd builddir/argos-${VERSION} && debuild -b -tc -us -uc && popd
