#!/bin/bash

cd "${MESON_SOURCE_ROOT}"

VERSION=$(poetry version | cut -d' ' -f 2)

BODY="See [News file](https://github.com/orontee/argos/blob/v${VERSION}/NEWS.rst) for release content.

Install from [Argos page on Flathub](https://flathub.org/apps/details/io.github.orontee.Argos) or the attached DEB package."

urlencode() {
  python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1], sys.argv[2]))" \
    "$1" "$urlencode_safe"
}
ENCODED_BODY=$(urlencode "${BODY}")

echo "Visit https://github.com/orontee/argos/releases/new?prerelease=1&tag=v${VERSION}&title=Release+v${VERSION}&body=${ENCODED_BODY}"
