#!/bin/bash

BUILDDIR=builddir

[ -d ${BUILDDIR} ] && {
    echo "Removing existing build directory…"
    rm -rf ${BUILDDIR}
}

mkdir ${BUILDDIR}

meson setup ${BUILDDIR} .
meson compile -C ${BUILDDIR} io.github.orontee.Argos-update-po
